# Generated by Django 3.0.8 on 2020-07-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size_in_inch', models.FloatField()),
                ('Style', models.CharField(max_length=200)),
                ('Clipart_name', models.CharField(max_length=200)),
                ('Clipart_image', models.ImageField(upload_to='')),
                ('Font_name', models.CharField(max_length=200)),
                ('Minimum_quantity', models.BigIntegerField()),
                ('Maximum_quantity', models.BigIntegerField()),
                ('Discount_percentage', models.FloatField()),
                ('Unit_price', models.IntegerField()),
                ('Status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Band_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Front_message', models.CharField(max_length=200)),
                ('Back_message', models.CharField(max_length=200)),
                ('Color', models.CharField(max_length=200)),
                ('Fonts_style', models.CharField(max_length=200)),
                ('Bandd_size', models.CharField(max_length=200)),
                ('Bandd_style', models.CharField(max_length=200)),
                ('Clipartt_name', models.CharField(max_length=200)),
                ('Quantitty', models.BigIntegerField()),
                ('Pricee', models.FloatField()),
                ('Totall_amount', models.FloatField()),
                ('First_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Phone', models.CharField(max_length=12)),
                ('State', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Pincode', models.BigIntegerField()),
                ('Address', models.TextField()),
                ('Order_date', models.DateField(auto_now_add=True)),
                ('Order_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=200)),
                ('Product_name', models.CharField(max_length=200)),
                ('Product_image', models.ImageField(upload_to='')),
                ('Minimum_quantity', models.BigIntegerField()),
                ('Maximum_quantity', models.BigIntegerField()),
                ('Discount_percentage', models.FloatField()),
                ('Unit_price', models.FloatField()),
                ('Status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Conveyance_fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delivery_charge_min_km', models.BigIntegerField()),
                ('Delivery_charge_max_km', models.BigIntegerField()),
                ('Delivery_fees', models.FloatField()),
                ('Shipping_days', models.BigIntegerField()),
                ('Shipping_description', models.TextField()),
                ('Shipping_cost', models.FloatField()),
                ('Status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=200)),
                ('Customer_email', models.EmailField(max_length=254)),
                ('Question', models.TextField()),
                ('Answer', models.TextField()),
                ('Submission_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Category', models.CharField(max_length=200)),
                ('Content', models.TextField()),
                ('Submission_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pre_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=200)),
                ('Product_name', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('First_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Phone', models.CharField(max_length=12)),
                ('State', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Pincode', models.BigIntegerField()),
                ('Address', models.TextField()),
                ('Quantity', models.IntegerField()),
                ('Order_date', models.DateField(auto_now_add=True)),
                ('Total_amount', models.FloatField()),
                ('Order_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation_cus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=200)),
                ('Customer_email', models.EmailField(max_length=254)),
                ('Category_name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Quantity_selected', models.BigIntegerField()),
                ('Quotation_date', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Phone', models.CharField(max_length=12)),
                ('Password', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Pincode', models.IntegerField()),
                ('Address', models.TextField()),
                ('About', models.TextField()),
                ('Lock', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=200)),
                ('Minimum_quantity', models.BigIntegerField()),
                ('Maximum_quantity', models.BigIntegerField()),
                ('Discount_percent', models.FloatField()),
                ('Status', models.CharField(max_length=200)),
                ('catt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silic.Category_product')),
            ],
        ),
        migrations.CreateModel(
            name='Cust_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Front_message', models.CharField(max_length=200)),
                ('Back_message', models.CharField(max_length=200)),
                ('Color', models.CharField(max_length=200)),
                ('Fon_style', models.CharField(max_length=200)),
                ('Ban_size', models.FloatField()),
                ('Ban_style', models.CharField(max_length=200)),
                ('Clippart_name', models.CharField(max_length=200)),
                ('QQuantity', models.BigIntegerField()),
                ('Pricce', models.FloatField()),
                ('Total_amount', models.FloatField()),
                ('Delivery_charge', models.FloatField()),
                ('regg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silic.Registration')),
            ],
        ),
    ]
